version: '3.6'

services:

  database:
    image: postgres:15-alpine3.17
    environment:
      - POSTGRES_PASSWORD=mysecretpassword     #https://hub.docker.com/_/postgres
      - PGDATA=/var/lib/postgresql/data/pgdata #https://hub.docker.com/_/postgres
    volumes:
      - pg_data:/var/lib/postgresql/data/pg_data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready' ]
      interval: 30s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: python manage.py migrate && python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/service
    ports:
      - "8080:8080"
    depends_on:
      database:
              condition: service_healthy

volumes:
  pg_data:


